name: Unzip File

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip File
        run: unzip yourfile.zip -d extracted_files

      - name: Commit and Push Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted_files
          git commit -m "Extracted ZIP file"
          git push origin mai
